/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.net.URL;
import javax.swing.JOptionPane;
import model.Person;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author harshaljaiswal
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    Person person;

    public CreatePanel(Person person) {
        initComponents();
        this.person = person;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        labName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        labGeoData = new javax.swing.JLabel();
        txtGeoData = new javax.swing.JTextField();
        labDob = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        labTelNo = new javax.swing.JLabel();
        txtTelNo = new javax.swing.JTextField();
        labFaxNo = new javax.swing.JLabel();
        labEmail = new javax.swing.JLabel();
        txtFaxNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        labSSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        labMedicalRec = new javax.swing.JLabel();
        txtMedRecNo = new javax.swing.JTextField();
        labHealthPlanNo = new javax.swing.JLabel();
        txtHealthPlanNo = new javax.swing.JTextField();
        labAccountNo = new javax.swing.JLabel();
        txtBankAccNo = new javax.swing.JTextField();
        labCertfNo = new javax.swing.JLabel();
        txtCertNo = new javax.swing.JTextField();
        labVehicleLicence = new javax.swing.JLabel();
        txtVehLicence = new javax.swing.JTextField();
        labDeviceSerialNo = new javax.swing.JLabel();
        txtDeviceNo = new javax.swing.JTextField();
        labLinkedin = new javax.swing.JLabel();
        labIntProtocolAdd = new javax.swing.JLabel();
        labBiometricId = new javax.swing.JLabel();
        txtLinkedIn = new javax.swing.JTextField();
        labUniqueId = new javax.swing.JLabel();
        txtIPA = new javax.swing.JTextField();
        labFullFacePhotos = new javax.swing.JLabel();
        txtBiometricId = new javax.swing.JTextField();
        txtUniqueId = new javax.swing.JTextField();
        labCreate = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnFileOpen = new javax.swing.JButton();
        txtFacePic = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        labName.setText("Name");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        labGeoData.setText("Geographic data/Address");

        txtGeoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeoDataActionPerformed(evt);
            }
        });

        labDob.setText("Date of Birth");

        labTelNo.setText("Telephone Number");

        labFaxNo.setText("Fax Number");

        labEmail.setText("Email address");

        labSSN.setText("Social Security Number");

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        labMedicalRec.setText("Medical record number");

        labHealthPlanNo.setText("Health Plan beneficiary No.");

        labAccountNo.setText("Bank Account Number");

        labCertfNo.setText("Certificate/license number");

        labVehicleLicence.setText("Vehicle licence plates");

        labDeviceSerialNo.setText("Device Serial Nimber");

        labLinkedin.setText("LinkedIn");

        labIntProtocolAdd.setText("Internet Protocol Addresses");

        labBiometricId.setText("Biometric identifiers");

        labUniqueId.setText("Unique Id");

        labFullFacePhotos.setText("Full Face Photo");

        txtBiometricId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBiometricIdActionPerformed(evt);
            }
        });

        labCreate.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labCreate.setText("Create");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnFileOpen.setText("Open File");
        btnFileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labEmail)
                    .addComponent(labFaxNo)
                    .addComponent(labTelNo)
                    .addComponent(labDob)
                    .addComponent(labGeoData)
                    .addComponent(labName)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labMedicalRec)
                        .addComponent(labSSN))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labAccountNo)
                            .addComponent(labHealthPlanNo)
                            .addComponent(labCertfNo)
                            .addComponent(labVehicleLicence)
                            .addComponent(labDeviceSerialNo)
                            .addComponent(labLinkedin)
                            .addComponent(labBiometricId)
                            .addComponent(labUniqueId)
                            .addComponent(labIntProtocolAdd)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFileOpen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labFullFacePhotos)))
                        .addGap(1, 1, 1)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(txtGeoData)
                    .addComponent(txtDob)
                    .addComponent(txtTelNo)
                    .addComponent(txtFaxNo)
                    .addComponent(txtEmail)
                    .addComponent(txtSSN)
                    .addComponent(txtMedRecNo)
                    .addComponent(txtHealthPlanNo)
                    .addComponent(txtBankAccNo)
                    .addComponent(txtCertNo)
                    .addComponent(txtVehLicence)
                    .addComponent(txtDeviceNo)
                    .addComponent(txtLinkedIn)
                    .addComponent(txtIPA)
                    .addComponent(txtBiometricId)
                    .addComponent(txtUniqueId)
                    .addComponent(txtFacePic))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(217, 217, 217))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labDob)
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTelNo)
                    .addComponent(txtTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labFaxNo)
                    .addComponent(txtFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labMedicalRec)
                    .addComponent(txtMedRecNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labHealthPlanNo)
                    .addComponent(txtHealthPlanNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labAccountNo)
                    .addComponent(txtBankAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labCertfNo)
                        .addGap(86, 86, 86)
                        .addComponent(labLinkedin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labIntProtocolAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labBiometricId))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCertNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVehLicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labVehicleLicence, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDeviceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labDeviceSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBiometricId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUniqueId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labUniqueId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labFullFacePhotos)
                            .addComponent(btnFileOpen)
                            .addComponent(txtFacePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtGeoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeoDataActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        boolean validData = this.validateData();

        if (validData) {
            person.setName(txtName.getText());
            person.setGeoData(txtGeoData.getText());
            person.setDob(txtDob.getText());
            person.setTelNumber(txtTelNo.getText());
            person.setFaxNumber(txtFaxNo.getText());
            person.setEmail(txtEmail.getText());
            person.setSsn(txtSSN.getText());
            person.setMedRecNumber(txtMedRecNo.getText());
            person.setHealthPlanNumber(txtHealthPlanNo.getText());
            person.setBankAccNumber(txtBankAccNo.getText());
            person.setCertfNumber(txtCertNo.getText());
            person.setLicencePlate(txtVehLicence.getText());
            person.setSerialNo(txtDeviceNo.getText());
            person.setLinkedIn(txtLinkedIn.getText());
            person.setInternetProtocolAdd(txtIPA.getText());
            person.setBiomerticIdentif(txtBiometricId.getText());
            person.setFace(txtFacePic.getText());
            person.setIdCode(txtUniqueId.getText());

            JOptionPane.showMessageDialog(this, "Person Details saved");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtBiometricIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBiometricIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiometricIdActionPerformed

    private void btnFileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileOpenActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        File f = new File("/Users/harshaljaiswal");
        file.setCurrentDirectory(f);

        FileNameExtensionFilter filter = new FileNameExtensionFilter("All Pictures", "png", "jpg", "jpeg", "gif");
        file.addChoosableFileFilter(filter);

        int a = file.showSaveDialog(null);
        if (a == JFileChooser.APPROVE_OPTION) {
            txtFacePic.setText(file.getSelectedFile().getAbsolutePath());
        }


    }//GEN-LAST:event_btnFileOpenActionPerformed

    protected class MainPane extends JPanel {

        private JFileChooser fileChooser;
        private JPanel filePane;

        private JTextField fileField;

        public MainPane() {

            setLayout(new BorderLayout());

            fileChooser = new JFileChooser();
            fileChooser.addPropertyChangeListener(new PropertyChangeListener() {

                public void propertyChange(PropertyChangeEvent evt) {
                    if (evt.getPropertyName().equals("SelectedFileChangedProperty")) {
                        File file = fileChooser.getSelectedFile();
                        if (file != null) {
                            setFile(file);
                        }
                    }
                }
            });

            add(fileChooser, BorderLayout.WEST);

            filePane = new JPanel(new GridBagLayout());
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.weightx = 1;
            gbc.fill = GridBagConstraints.HORIZONTAL;

            fileField = new JTextField(10);
            filePane.add(fileField, gbc);

            add(filePane);

        }

        protected void setFile(File file) {

            fileField.setText(file.getPath());

        }

    }

    public boolean validateData() {

        if (txtName.getText().length() < 1) {
            JOptionPane.showMessageDialog(this, "Enter proper Name");
            return false;
        }

        if (txtGeoData.getText().length() < 1) {
            JOptionPane.showMessageDialog(this, "Enter proper Location/Address");
            return false;
        }

        if (!isValidDate(txtDob.getText())) {
            JOptionPane.showMessageDialog(this, "Enter proper date in mm/dd/yyyy format");
            return false;
        }

        if ( !txtTelNo.getText().matches("[0-9]+") ||  txtTelNo.getText().length() != 10 ) {
            JOptionPane.showMessageDialog(this, "Enter proper 10 digit Telephone Number");
            return false;
        }

        if (!txtTelNo.getText().matches("[0-9]+") ||  txtFaxNo.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Enter proper 10 digit Fax Number");
            return false;
        }

        if (!isValidEmail(txtEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Enter proper Email Address");
            return false;
        }

        if ( !txtTelNo.getText().matches("[0-9]+") || txtSSN.getText().length() != 9) {
            JOptionPane.showMessageDialog(this, "Enter proper 9 digit SSN number");
            return false;
        }

        if ( !txtTelNo.getText().matches("[0-9]+") || txtMedRecNo.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Enter proper 10 digit Medical Record Number");
            return false;
        }

        if ( !txtTelNo.getText().matches("[0-9]+") || txtHealthPlanNo.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Enter proper 10 digit Health plan Number");
            return false;
        }

        if (!txtTelNo.getText().matches("[0-9]+") || txtBankAccNo.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Enter proper 10 digit Bank Account Number");
            return false;
        }

        if (txtCertNo.getText().length() != 6) {
            JOptionPane.showMessageDialog(this, "Enter proper 6 digit Alpha Numeric Certificate Number");
            return false;
        }

        if (txtVehLicence.getText().length() != 6) {
            JOptionPane.showMessageDialog(this, "Enter proper 6 digit alpha numeric Licence plate");
            return false;
        }

        if ( !txtTelNo.getText().matches("[0-9]+") || txtDeviceNo.getText().length() != 4) {
            JOptionPane.showMessageDialog(this, "Enter proper 4 digit Device Serial Number");
            return false;
        }

        if (!isURLValid(txtLinkedIn.getText())) {
            JOptionPane.showMessageDialog(this, "Enter proper Url for LinkedIn");
            return false;
        }

        if (!isValidIPAddress(txtIPA.getText())) {
            JOptionPane.showMessageDialog(this, "Enter proper Ip Address like \"000.12.12.034\" ");
            return false;
        }

        if (txtBiometricId.getText().length() != 5) {
            JOptionPane.showMessageDialog(this, "Enter proper 5 digit Biometric ID");
            return false;
        }

        if (txtUniqueId.getText().length() < 1) {
            JOptionPane.showMessageDialog(this, "Enter proper Unique Id");
            return false;
        }

        if (txtFacePic.getText().length() < 1) {
            JOptionPane.showMessageDialog(this, "Please add Face Picture");
            return false;
        }

        return true;

    }

    public static boolean isValidIPAddress(String ip) {

        String zeroTo255
                = "(\\d{1,2}|(0|1)\\"
                + "d{2}|2[0-4]\\d|25[0-5])";

        String regex
                = zeroTo255 + "\\."
                + zeroTo255 + "\\."
                + zeroTo255 + "\\."
                + zeroTo255;

        Pattern p = Pattern.compile(regex);

        if (ip == null) {
            return false;
        }
        Matcher m = p.matcher(ip);
        return m.matches();
    }

    public static boolean isURLValid(String url) {
        try {
            new URL(url).toURI();
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    public static boolean isValidEmail(String email) {
        Pattern regexPattern = Pattern.compile("^[(a-zA-Z-0-9-\\_\\+\\.)]+@[(a-z-A-z)]+\\.[(a-zA-z)]{2,3}$");
        Matcher regMatcher = regexPattern.matcher(email);

        if (regMatcher.matches()) {
            return true;
        } else {
            return false;
        }
    }

    public static boolean isValidDate(String strDate) {
        if (strDate.trim().equals("")) {
            return true;
        } else {

            SimpleDateFormat sdfrmt = new SimpleDateFormat("MM/dd/yyyy");
            sdfrmt.setLenient(false);

            try {
                Date javaDate = sdfrmt.parse(strDate);
            } catch (ParseException e) {
                return false;
            }
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFileOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel labAccountNo;
    private javax.swing.JLabel labBiometricId;
    private javax.swing.JLabel labCertfNo;
    private javax.swing.JLabel labCreate;
    private javax.swing.JLabel labDeviceSerialNo;
    private javax.swing.JLabel labDob;
    private javax.swing.JLabel labEmail;
    private javax.swing.JLabel labFaxNo;
    private javax.swing.JLabel labFullFacePhotos;
    private javax.swing.JLabel labGeoData;
    private javax.swing.JLabel labHealthPlanNo;
    private javax.swing.JLabel labIntProtocolAdd;
    private javax.swing.JLabel labLinkedin;
    private javax.swing.JLabel labMedicalRec;
    private javax.swing.JLabel labName;
    private javax.swing.JLabel labSSN;
    private javax.swing.JLabel labTelNo;
    private javax.swing.JLabel labUniqueId;
    private javax.swing.JLabel labVehicleLicence;
    private javax.swing.JTextField txtBankAccNo;
    private javax.swing.JTextField txtBiometricId;
    private javax.swing.JTextField txtCertNo;
    private javax.swing.JTextField txtDeviceNo;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFacePic;
    private javax.swing.JTextField txtFaxNo;
    private javax.swing.JTextField txtGeoData;
    private javax.swing.JTextField txtHealthPlanNo;
    private javax.swing.JTextField txtIPA;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedRecNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTelNo;
    private javax.swing.JTextField txtUniqueId;
    private javax.swing.JTextField txtVehLicence;
    // End of variables declaration//GEN-END:variables
}
